### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by Tortoise17** [modelscope/3D-Speaker#119]
`AssertionError: Model_id is not currently supported.`

the command used is 

```
model_id=iic/speech_eres2net_sv_zh-cn_16k-common
python speakerlab/bin/infer_sv_ssl.py --model_id $model_id --wavs ../input.wav
```

kindly if you can give the hint to resolve this issue.

**Comment by qiqi0308** [comment]
> `AssertionError: Model_id is not currently supported.`
> 
> the command used is
> 
> ```
> model_id=iic/speech_eres2net_sv_zh-cn_16k-common
> python speakerlab/bin/infer_sv_ssl.py --model_id $model_id --wavs ../input.wav
> ```
> 
> kindly if you can give the hint to resolve this issue.

I fail in this as well as you
