### ISSUE TITLE
Inference index info in indentification from trained model

### ISSUE THREAD

**Issue by Tortoise17** [modelscope/3D-Speaker#120]
I have tried 

`python speakerlab/bin/infer_sv.py --model_id $model_id --wavs input.wav`

This exports the numpy array file. How can I get the inference info from trained model that this object is corresponding to which speaker number or which speaker in terms of identification?

If you could guide me.

**Comment by yfchenlucky** [comment]
https://github.com/modelscope/3D-Speaker/blob/main/speakerlab/bin/infer_sv.py#L290-L291

**Comment by Tortoise17** [comment]
@yfchenlucky Great, thank you. If I have to match one wav with files form folder, which has multiple. Could this be possible? to make closest top1-2 matches.?

**Comment by Tortoise17** [comment]
I guess little change in pipeline will match the possible closest index. Thank you again. If there is still problem, I will request for help.

**Comment by yfchenlucky** [comment]
There are many ways. If you don't want to change the code, you can construct wav1, wav2\n wav1 wav3\n and so on, then test pairs and calculate the scores. Or you can simply modify infer_sv.py by fixing the enroll wav and constantly changing the test wav.

**Comment by Tortoise17** [comment]
@yfchenlucky Great help. Really excellent work. Super top architecture models.
