### ISSUE TITLE
请教language-identification语料时数问题

### ISSUE THREAD

**Issue by jeremy110** [modelscope/3D-Speaker#123]
您好，我想训练四种语种，所以我将CAM++语种识别-中英粤日韩识别-16k当中的embedding model来初始化我的model，然后四种语种的训练时数分别为250h, 250h , 500h, 200h，每跑一个epoch 我就测试一次eval和test，test前一两个epoch acc有8成，但后面就逐渐往下掉6~7成，eval一直往上升到9成多，所以我认为是overfitting 。

想请问训练多语种，各个的时数大概需要多少，以及跟spk数量会有关系吗?

**Comment by yfchenlucky** [comment]
如果eval和train同源，而test与eval不同源的话，看起来是overfitting导致。训练4语种，各语种训练时长在500h-5kh应该都可以获得较有性能，与spk数量相关性我们没有研究。你可以尝试 https://github.com/modelscope/3D-Speaker/blob/main/egs/3dspeaker/language-identification/run_paraformer.sh 是最佳训练策略，极大减小过拟合概率。

**Comment by jeremy110** [comment]
感谢您快速地回复，我会再试试看的

**Comment by yfchenlucky** [comment]
可能是和中英台客训练语音占比有关，台是什么语种？客是客家话吗？
1. 尝试增加台客训练语音占比。
2. 可以适当以小学习率微调所有模型参数。

**Comment by jeremy110** [comment]
感谢您快速地回复

台是台湾闽南语，客是客家话没错，是客家话没错，时数的部分，都照上次数值，全部都500小时。

我会再尝试增加台客比例
那想请问微调所有模型参数，所需要的GPU记忆体? 因为目前我是在2080ti 12G底下做训练的。

**Comment by yfchenlucky** [comment]
单语种时长可以增加至>1kh，实验效果更佳。
32G V100可以满足微调需求，该项目所有实验都是在该配置下完成。期待你的进一步提升！
请多多宣传我们的项目，star&fork，感谢！

**Comment by jeremy110** [comment]
感谢您的资讯，我会再尝试的

**Comment by jeremy110** [comment]
作者您好，照您的建议我有训练出来了，我台语跟客语都增加到1000h以上，然后我解冻5~10层的ASR encoder，以下是这次的confusion matrix

![image](https://github.com/user-attachments/assets/ee302b9c-4216-41f9-8597-1a8137cf880c)


非常感谢帮忙，另外想再请问，假设我随便拿个日语或西班牙語的音档辨识，模型一定只能回中英台客其中一个，有没有什么办法，回复unk也就是不在你训练的语种当中?

**Comment by yfchenlucky** [comment]
因为最后是通过分类器进行四选一，所以如果你想输出unk可以在softmax之前的输出进行阈值筛选，如果四个语种输出概率都降低那么判断成unk。
另外您可以将仓库中新增代码重构并pull request吗？贡献出你的一份力，共建社区繁荣！感谢

**Comment by jeremy110** [comment]
感谢您的回覆，这部分我可能再试一下。

我的code是重新用pytorch lightning框架写过，可能差有点多，也可能有问题，不知道能否推到我的git请你帮我看是否有错?

**Comment by yfchenlucky** [comment]
这样啊？那可能有些麻烦，没事儿如果您有时间的话可以在我们仓库上直接修改提交。

**Comment by jeremy110** [comment]
好的，没问题，我有将para的部分从funasr抽出来，并且将model参数只留下encoder的部分，程式简化方面应该会有帮助，这部分如果需要后续一并提供，感谢。
我先去解决我训练的问题，还有些小bug。

**Comment by jiayuan666** [comment]
同胞你好 @jeremy110 我也在做类似的工作，请教一下您，您训练时超参数配置上相比原始配置做了什么调整呢？例如学习率、训练测试集配比等。万分感谢

**Comment by jeremy110** [comment]
@jiayuan666 
我沒有特別去計算他們的配比，lr好像照原始的吧，主要測試集採outside test 每個語言各6000筆，訓練資料四個語言"比數"要接近，而不是"小時數"接近，然後如果你是要訓練其他語言，可以嘗試將asr encoder凍結幾層，讓他可以學習到其他語言。

**Comment by p1an-lin-jung** [comment]
您好，我也在做一個 閩南語-普通話-英語的三分類模型，每種語料都是100小時左右，用於filter數據。現在訓練出來只有40%多的準確率，是否需要調整一些參數或者增加數據量？

**Comment by jeremy110** [comment]
@p1an-lin-jung 
你好，可以再增加時數看看，應該300小時會比較好。
因為閩南語不在原先asr encoder的訓練裡面，所以你可以解凍幾層讓他學習閩南語。

**Comment by p1an-lin-jung** [comment]
> @p1an-lin-jung 你好，可以再增加時數看看，應該300小時會比較好。 因為閩南語不在原先asr encoder的訓練裡面，所以你可以解凍幾層讓他學習閩南語。

我換成para模型，調低learning rate之後，在訓練集上的準確率到了99%以上，但是它還是會把閩南口音的普通話識別成閩南語_^_^_

**Comment by jeremy110** [comment]
@p1an-lin-jung 
這方面確實比較難，可能要再多加這類的資料下去訓練。
