### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Onlyooo** [modelscope/3D-Speaker#124]
我想跑通这个CAM++模型的时候遇到了
![1721024757886](https://github.com/user-attachments/assets/d113713e-2a4e-4df1-8df4-09c17d7b6116)
请问这个怎么解决？

**Comment by yfchenlucky** [comment]
Wav文件没准备好，请从stage1开始运行并确认文件是否存在且正确。

**Comment by Onlyooo** [comment]
明白了谢谢您，还想请问如果我想做关于声音识别杂音这样的项目，应该通过哪个项目中的哪个网络比较好呢？

**Comment by yfchenlucky** [comment]
ERes2NetV2, CAM++, ECAPA-TDNN都可以试试。
