### ISSUE TITLE
训练CAM++时的问题

### ISSUE THREAD

**Issue by HaoFengyuan** [modelscope/3D-Speaker#127]
你好，在训练CAM++的时候提示在File"/ssd/data4/kolson.Hao/ Project/3D-speaker/speakerlab/process/processor·py",1ine 128中使用torchaudio.load导入音频出错

![lQLPJxQqI721bD_NAzHNBWCwuShap87hAogGioJRb5e-AQ_1376_817](https://github.com/user-attachments/assets/4637afa7-4647-44ed-98df-89c3ac795a84)
![lQLPKG17NKqMLT_NAqXNBZGwXOpinGq-FnwGioJRb5e-AA_1425_677](https://github.com/user-attachments/assets/27b1614b-5775-4253-a941-1b747a6460ca)

**Comment by yfchenlucky** [comment]
报错的那行代码加入backend：wav, sr = torchaudio.load(*, backend="sox")  因为ffmpeg处理不了30 channels的音频，所以只在增强阶段报错，我们后续会修改代码
