### ISSUE TITLE
如何使用自己的声纹文件进行模型训练

### ISSUE THREAD

**Issue by smengfei** [modelscope/3D-Speaker#129]
模型训练过程中碰到几个问题不知如何操作：
1、我使用3D-Speaker/egs/voxceleb/sv-cam++/run.sh脚本进行训练，训练完成后有4个文件，分别是CKPT.yaml和classifier.ckpt和embedding_model.ckpt和epoch_counter.ckpt，我该怎么使用这几个文件进行声纹识别
2、我该怎么使用自己的声纹进行训练，是用自己的声纹训练是，是在魔搭提供的预训练模型的基础上进行训练的还是从零开始训练

**Comment by yfchenlucky** [comment]
1. 参考推理过程，使用embedding_model.ckpt提取speaker embeddings后面使用相似度打分来判断是否属于同一说话人，代码见：https://github.com/modelscope/3D-Speaker/blob/main/egs/3dspeaker/sv-cam%2B%2B/run.sh#L40-L53
