### ISSUE TITLE
speakerlab/process/augmentation.py addnoise function has undefined symbol

### ISSUE THREAD

**Issue by laishuzhong** [modelscope/3D-Speaker#130]
def addnoise(wav, noise=None, snr_high=15, snr_low=0):
    # wav: [T,], noise: [T,]
    if noise is None:
        noise = torch.randn_like(waveform)
    noise = noise.numpy()
    wav = wav.numpy()
    ...

symbol "waveform" is not defined, I guess it may be "wav".

**Comment by yfchenlucky** [comment]
Thank you for your correction. The error has now been fixed.
