### ISSUE TITLE
语种识别，怎么将modelscope里的模型对应上

### ISSUE THREAD

**Issue by wjyfelicity** [modelscope/3D-Speaker#133]
用3D-Speaker/egs/3dspeaker/language-identification/run.sh跑出来的模型有三个，CKPT.yaml  classifier.ckpt  embedding_model.ckpt  epoch_counter.ckpt  label_encoder.ckpt
而modelscope里的模型只有两个：
![ihsq19sMbK](https://github.com/user-attachments/assets/018553c3-b99f-4ad2-8823-2d7994443a64)
而且配置文件也不一样，请问要怎么对应上？

**Comment by yfchenlucky** [comment]
CKPT.yaml 在推理阶段不需要使用，是模型训练阶段保存的文件。
