### ISSUE TITLE
About ASR with Speaker Diarization pipeline

### ISSUE THREAD

**Issue by yChenN1** [modelscope/3D-Speaker#134]
After obtaining the speaker labels from speaker diarization, How can we use it to generate a transcript with speaker labels?  or how to combine those two parts?

**Comment by yfchenlucky** [comment]
You can try this model: https://modelscope.cn/models/iic/speech_campplus_speaker-diarization_common

**Comment by yChenN1** [comment]
I tried it, but it can only achieve speaker diarization. The point is to combine ASR with Speaker diarization.

**Comment by yChenN1** [comment]
Could it be used with ASR to assign speaker labels to each text transcription?
