### ISSUE TITLE
与FunClip在说话人识别上的比较

### ISSUE THREAD

**Issue by yumianhuli1** [modelscope/3D-Speaker#137]
与FunClip在说话人识别上相比，是不是多了视频视觉和语义两个维度？谢谢！

**Comment by yfchenlucky** [comment]
FunClip is a fully open-source, locally deployed automated video clipping tool. Its features lie in its applications, incorporating some functionalities of funasr and 3d-speaker. This project is an open-source toolkit for single- and multi-modal speaker verification, speaker recognition, and speaker diarization, not limited to the multimodal aspects of diarization. For more details, you can refer to our article: https://arxiv.org/pdf/2403.19971.

**Comment by yumianhuli1** [comment]
> FunClip is a fully open-source, locally deployed automated video clipping tool. Its features lie in its applications, incorporating some functionalities of funasr and 3d-speaker. This project is an open-source toolkit for single- and multi-modal speaker verification, speaker recognition, and speaker diarization, not limited to the multimodal aspects of diarization. For more details, you can refer to our article: https://arxiv.org/pdf/2403.19971.

好的，我主要是想先定性了解一下，如果FunClip中确定spk id的正确率是80%，那利用多模态（语音、视觉、语义）联合估计的正确率大概能到一个什么水平？谢谢!

**Comment by yfchenlucky** [comment]
There isn't an exact measurement, but it can be certain that the accuracy will definitely be higher than 80%.

**Comment by yumianhuli1** [comment]
> There isn't an exact measurement, but it can be certain that the accuracy will definitely be higher than 80%.

ok
