### ISSUE TITLE
The voxceleb dataset is not available for download

### ISSUE THREAD

**Issue by gray5wolf** [modelscope/3D-Speaker#142]
When I download the dataset with download_data.sh, the following error occurs：
Downloading vox1_test_wav.zip ...
--2024-10-11 07:49:13--  https://thor.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_test_wav.zip
正在解析主机 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 129.67.95.98
正在连接 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)|129.67.95.98|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 308 Permanent Redirect
位置：https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_test_wav.zip [跟随至新的 URL]
--2024-10-11 07:49:15--  https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_test_wav.zip
再次使用存在的到 thor.robots.ox.ac.uk:443 的连接。
已发出 HTTP 请求，正在等待回应... 401 Unauthorized

用户名/密码认证失败。
md5sum: data/download_data/vox1_test_wav.zip: 没有那个文件或目录
./download_data.sh: 第 42 行： [: !=: 需要一元运算符
Downloading vox1_dev_wav.zip ...
--2024-10-11 07:49:15--  https://thor.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa
--2024-10-11 07:49:15--  https://thor.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partac
--2024-10-11 07:49:15--  https://thor.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partad
--2024-10-11 07:49:15--  https://thor.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partab
正在解析主机 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 正在解析主机 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 正在解析主机 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 正在解析主机 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 129.67.95.98
129.67.95.98
正在连接 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)|129.67.95.98|:443... 正在连接 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)|129.67.95.98|:443... 129.67.95.98
正在连接 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)|129.67.95.98|:443... 129.67.95.98
正在连接 thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)|129.67.95.98|:443... 已连接。
已连接。
已连接。
已连接。
已发出 HTTP 请求，正在等待回应... 已发出 HTTP 请求，正在等待回应... 已发出 HTTP 请求，正在等待回应... 已发出 HTTP 请求，正在等待回应... 308 Permanent Redirect
位置：https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_dev_wav_partac [跟随至新的 URL]
--2024-10-11 07:49:16--  https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_dev_wav_partac
再次使用存在的到 thor.robots.ox.ac.uk:443 的连接。
已发出 HTTP 请求，正在等待回应... 308 Permanent Redirect
位置：https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_dev_wav_partad [跟随至新的 URL]
--2024-10-11 07:49:16--  https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_dev_wav_partad
再次使用存在的到 thor.robots.ox.ac.uk:443 的连接。
已发出 HTTP 请求，正在等待回应... 308 Permanent Redirect
位置：https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_dev_wav_partab [跟随至新的 URL]
--2024-10-11 07:49:16--  https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_dev_wav_partab
再次使用存在的到 thor.robots.ox.ac.uk:443 的连接。
已发出 HTTP 请求，正在等待回应... 308 Permanent Redirect
位置：https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_dev_wav_partaa [跟随至新的 URL]
--2024-10-11 07:49:16--  https://thor.robots.ox.ac.uk/voxceleb/vox1a/vox1_dev_wav_partaa
再次使用存在的到 thor.robots.ox.ac.uk:443 的连接。
已发出 HTTP 请求，正在等待回应... 401 Unauthorized

用户名/密码认证失败。
401 Unauthorized

用户名/密码认证失败。
401 Unauthorized

用户名/密码认证失败。
401 Unauthorized

用户名/密码认证失败。
cat: 'data/download_data/vox1_dev*': 没有那个文件或目录
Wrong md5sum of vox1_dev_wav.zip
so how can I solve it？

**Comment by yfchenlucky** [comment]
Yes, there is indeed an issue with downloading the VoxCeleb data. VoxCeleb can now only be downloaded from the official website due to copyright issues, we are unable to resolve this problem. You might consider using the 3dspeaker datasets as an alternative. The download link is: https://3dspeaker.github.io/#Download.
