### ISSUE TITLE
训练数据替换和断点恢复训练

### ISSUE THREAD

**Issue by zhangzh16** [modelscope/3D-Speaker#143]
开发者您好，非常感谢您的开源贡献！
1.我使用ecapatdnn-vox2dev的训练框架和代码，利用自己的四个数据集生成了四个文件夹（里面包含wav.scp, utt2spk, spk2utt, train.csv等），在使用四个数据集训练ecapatdnn模型，现在的方法是将四个train.csv拼成一个csv，当作一个大数据集训练。想问下能否实现输入参数是多个训练集，例如--data $data/a.csv --data $data/b.csv --data $data/c.csv这样的
2.在训练过程中由于机器断电关机导致训练中断，设置默认70个epoch，在恢复训练时应该如何设置载入模型参数以及相应的学习策略？
期待您的回复

**Comment by yfchenlucky** [comment]
直接重新运行即可，代码中有断点恢复功能。
