### ISSUE TITLE
如何微调ERes2NetV2_w24s4ep4模型

### ISSUE THREAD

**Issue by kwaihua** [modelscope/3D-Speaker#145]
我自己构建了一批说话人数据集，我看ERes2NetV2模型只有在不同数据集下训练的脚本，如果我想在ERes2NetV2_w24s4ep4预训练模型的基础上进行微调应该如何操作呢？

**Comment by tebie6** [comment]
@kwaihua 你好，有找到方案嘛，我也在尝试在ERes2NetV2_w24s4ep4基础上做微调

**Comment by yfchenlucky** [comment]
可以参考 https://github.com/modelscope/3D-Speaker/blob/main/egs/3dspeaker/sv-eres2netv2/run.sh 代码中stage4，先load ERes2NetV2_w24s4ep4模型，再使用准备好的train.csv训练数据finetune模型，注意调小学习率等参数。
