### ISSUE TITLE
关于train.csv

### ISSUE THREAD

**Issue by huayu-2049** [modelscope/3D-Speaker#148]
请为什么使用 sv 中的 repare_data_csv.py 后，train.csv 所得到的内容中，很多的音频文件并没有被用到 ，比如id00012/21Uxsk56VDQ/00001.wav 就没有被用到，而是直接从  id00012/21Uxsk56VDQ/00002.wav 开始的，且最后按4s分割后的语音段数841887，证明很多的音频都没有用到，是哪一步筛选了吗

**Comment by yfchenlucky** [comment]
训练数据中有效音频都是被使用的，可能长度过短导致音频拼接，你可以仔细检索wav名称。

**Comment by huayu-2049** [comment]
好的，我再检查一下，感谢！
