### ISSUE TITLE
EER 差异过大

### ISSUE THREAD

**Issue by axyzstra** [modelscope/3D-Speaker#151]
您好，非常感谢您的开源贡献！

我在复现过程中遇到了两个问题。

第一个问题是：

我在使用 [[ecapa 英文预训练模型](https://www.modelscope.cn/models/iic/speech_ecapa-tdnn_sv_en_voxceleb_16k/summary)](https://www.modelscope.cn/models/iic/speech_ecapa-tdnn_sv_en_voxceleb_16k/summary) 在 `VoxCeleb1-O` 测试集上只获得了如下结果：

```shell
Results of vox1_O_cleaned.trial is:
EER = 4.9516
minDCF (p_target:0.01 c_miss:1 c_fa:1) = 0.4238
```

和公布的 `EER = 0.862%，minDCF(p_target=0.01, c_miss=c_fa=1) = 0.094` 相去甚远。以下是我加载预训练模型的代码：

```python
...
path = "3D-Speaker/egs/voxceleb/sv-ecapa/model/ecapa_tdnn.bin"
embedding_model.load_state_dict(torch.load(path, map_location=device))

# Recover the embedding params of last epoch
# config.checkpointer['args']['checkpoints_dir'] = os.path.join(args.exp_dir, 'models')
# config.checkpointer['args']['recoverables'] = {'embedding_model':embedding_model}
# checkpointer = build('checkpointer', config)
# checkpointer.recover_if_possible(epoch=config.num_epoch, device=device)

embedding_model.to(device)
embedding_model.eval()
feature_extractor = build('feature_extractor', config)
...
```

训练脚本：

```shell
if [ ${stage} -le 4 ] && [ ${stop_stage} -ge 4 ]; then
  # Extract embeddings of test datasets.
  echo "Stage4: Extracting speaker embeddings..."
  num_gpu=$(echo $gpus | awk -F ' ' '{print NF}')
  torchrun --nproc_per_node=$num_gpu --master_port=29531 speakerlab/bin/extract.py --exp_dir $exp_dir \
           --data $data/vox1/wav.scp --use_gpu --gpu $gpus > output/extract.txt 2>&1
fi

if [ ${stage} -le 5 ] && [ ${stop_stage} -ge 5 ]; then
  # Output score metrics.
  echo "Stage5: Computing score metrics..."
  trials="$data/vox1/trials/vox1_O_cleaned.trial"
  python speakerlab/bin/compute_score_metrics.py --enrol_data $exp_dir/embeddings --test_data $exp_dir/embeddings \
                                                 --scores_dir $exp_dir/scores --trials $trials > output/score.txt 2>&1
fi
```

第二个问题：

我使用 `voxceleb1` 的开发集进行训练 `ECAPA-TDNN` 模型，只修改了脚本中的训练数据集部分。得到以下结果：

```shell
Results of vox1_O_cleaned.trial is:
EER = 0.3137
minDCF (p_target:0.01 c_miss:1 c_fa:1) = 0.0242
```

这个结果感觉很奇怪，比预训练模型的结果好得多，但是我训练的数据集只是 `voxceleb1` 的开发集部分。

**Comment by wanghuii1** [comment]
1. 经过测试的结果无误Equal error rate is 0.86161%, at threshold 0.381932。请检查你的test脚本，参考speakerlab/bin/infer_sv.py提取特征（设置model_id=iic/speech_ecapa-tdnn_sv_en_voxceleb_16k），参考speakerlab/bin/compute_score_metrics.py计算得分即相似度。
2. paper中是使用voxceleb2的开发集进行训练，非voxceleb1开发集

**Comment by axyzstra** [comment]
好的，感谢回答。我取检查检查。

**Comment by uuuzk** [comment]
您好，我也同样遇到了这个问题，在使用原来的python egs/voxceleb/sv-cam++/speakerlab/bin/train.py训练代码和原始的配置文件进行训练，，未修改代码，训练收敛速度和训练性能与一般的VoxCeleb2-dev训练模型模型和仓库中提供的性能差距甚远，请问您当时是怎么解决这个问题的？或者作者是否解决过类似issue？

**Comment by uuuzk** [comment]
补充，部分训练日志：
epoch: 1 - train Avg_loss: 7.08, train Avg_acc: 6.52, train Lr_value: 2.01e-02, train Sum_time: 83.86, train Eval_EER: 16.55, train Best_EER: 16.55
epoch: 2 - train Avg_loss: 3.14, train Avg_acc: 37.30, train Lr_value: 4.01e-02, train Sum_time: 83.75, train Eval_EER: 11.90, train Best_EER: 11.90
epoch: 3 - train Avg_loss: 1.89, train Avg_acc: 60.18, train Lr_value: 6.00e-02, train Sum_time: 84.50, train Eval_EER: 9.43, train Best_EER: 9.43
epoch: 4 - train Avg_loss: 1.84, train Avg_acc: 61.72, train Lr_value: 8.00e-02, train Sum_time: 82.43, train Eval_EER: 11.51, train Best_EER: 9.43
epoch: 5 - train Avg_loss: 2.07, train Avg_acc: 57.90, train Lr_value: 1.00e-01, train Sum_time: 81.52, train Eval_EER: 12.24, train Best_EER: 9.43
epoch: 6 - train Avg_loss: 2.43, train Avg_acc: 52.27, train Lr_value: 9.99e-02, train Sum_time: 83.01, train Eval_EER: 9.78, train Best_EER: 9.43
epoch: 7 - train Avg_loss: 1.88, train Avg_acc: 62.43, train Lr_value: 9.97e-02, train Sum_time: 83.29, train Eval_EER: 9.88, train Best_EER: 9.43
epoch: 8 - train Avg_loss: 2.07, train Avg_acc: 59.36, train Lr_value: 9.93e-02, train Sum_time: 85.80, train Eval_EER: 10.07, train Best_EER: 9.43
epoch: 9 - train Avg_loss: 2.09, train Avg_acc: 59.12, train Lr_value: 9.87e-02, train Sum_time: 86.20, train Eval_EER: 10.20, train Best_EER: 9.43
epoch: 10 - train Avg_loss: 1.93, train Avg_acc: 62.26, train Lr_value: 9.80e-02, train Sum_time: 85.16, train Eval_EER: 10.76, train Best_EER: 9.43
epoch: 11 - train Avg_loss: 1.85, train Avg_acc: 63.75, train Lr_value: 9.71e-02, train Sum_time: 85.01, train Eval_EER: 10.06, train Best_EER: 9.43
epoch: 12 - train Avg_loss: 1.93, train Avg_acc: 62.43, train Lr_value: 9.61e-02, train Sum_time: 83.00, train Eval_EER: 10.08, train Best_EER: 9.43
epoch: 13 - train Avg_loss: 2.01, train Avg_acc: 61.07, train Lr_value: 9.49e-02, train Sum_time: 83.20, train Eval_EER: 9.22, train Best_EER: 9.22
epoch: 14 - train Avg_loss: 1.73, train Avg_acc: 66.32, train Lr_value: 9.35e-02, train Sum_time: 81.92, train Eval_EER: 10.07, train Best_EER: 9.22
epoch: 15 - train Avg_loss: 1.77, train Avg_acc: 65.58, train Lr_value: 9.21e-02, train Sum_time: 81.81, train Eval_EER: 10.79, train Best_EER: 9.22
epoch: 16 - train Avg_loss: 3.17, train Avg_acc: 59.58, train Lr_value: 9.05e-02, train Sum_time: 82.07, train Eval_EER: 10.39, train Best_EER: 9.22
epoch: 17 - train Avg_loss: 4.72, train Avg_acc: 60.07, train Lr_value: 8.87e-02, train Sum_time: 81.83, train Eval_EER: 13.71, train Best_EER: 9.22
epoch: 18 - train Avg_loss: 5.58, train Avg_acc: 60.55, train Lr_value: 8.69e-02, train Sum_time: 81.15, train Eval_EER: 9.51, train Best_EER: 9.22
epoch: 19 - train Avg_loss: 5.92, train Avg_acc: 61.70, train Lr_value: 8.49e-02, train Sum_time: 80.28, train Eval_EER: 9.89, train Best_EER: 9.22
epoch: 20 - train Avg_loss: 6.22, train Avg_acc: 61.06, train Lr_value: 8.28e-02, train Sum_time: 81.37, train Eval_EER: 10.64, train Best_EER: 9.22
epoch: 21 - train Avg_loss: 6.27, train Avg_acc: 61.73, train Lr_value: 8.06e-02, train Sum_time: 80.46, train Eval_EER: 11.76, train Best_EER: 9.22
epoch: 22 - train Avg_loss: 6.22, train Avg_acc: 62.74, train Lr_value: 7.82e-02, train Sum_time: 79.60, train Eval_EER: 11.02, train Best_EER: 9.22
epoch: 23 - train Avg_loss: 6.33, train Avg_acc: 62.08, train Lr_value: 7.58e-02, train Sum_time: 79.78, train Eval_EER: 11.26, train Best_EER: 9.22
epoch: 24 - train Avg_loss: 6.27, train Avg_acc: 62.75, train Lr_value: 7.34e-02, train Sum_time: 79.61, train Eval_EER: 9.17, train Best_EER: 9.17
epoch: 25 - train Avg_loss: 6.36, train Avg_acc: 62.00, train Lr_value: 7.08e-02, train Sum_time: 79.83, train Eval_EER: 10.79, train Best_EER: 9.17
epoch: 26 - train Avg_loss: 6.31, train Avg_acc: 62.57, train Lr_value: 6.82e-02, train Sum_time: 80.81, train Eval_EER: 11.27, train Best_EER: 9.17
epoch: 27 - train Avg_loss: 6.08, train Avg_acc: 64.64, train Lr_value: 6.55e-02, train Sum_time: 80.27, train Eval_EER: 9.37, train Best_EER: 9.17
epoch: 28 - train Avg_loss: 6.13, train Avg_acc: 64.52, train Lr_value: 6.27e-02, train Sum_time: 81.15, train Eval_EER: 8.44, train Best_EER: 8.44
epoch: 29 - train Avg_loss: 5.78, train Avg_acc: 67.64, train Lr_value: 6.00e-02, train Sum_time: 79.92, train Eval_EER: 8.56, train Best_EER: 8.44
epoch: 30 - train Avg_loss: 5.96, train Avg_acc: 66.03, train Lr_value: 5.72e-02, train Sum_time: 82.05, train Eval_EER: 10.18, train Best_EER: 8.44
epoch: 31 - train Avg_loss: 5.90, train Avg_acc: 66.72, train Lr_value: 5.43e-02, train Sum_time: 84.47, train Eval_EER: 10.17, train Best_EER: 8.44
epoch: 32 - train Avg_loss: 5.91, train Avg_acc: 66.65, train Lr_value: 5.15e-02, train Sum_time: 82.84, train Eval_EER: 8.49, train Best_EER: 8.44
epoch: 33 - train Avg_loss: 5.60, train Avg_acc: 69.38, train Lr_value: 4.86e-02, train Sum_time: 82.85, train Eval_EER: 8.09, train Best_EER: 8.09
epoch: 34 - train Avg_loss: 5.70, train Avg_acc: 68.65, train Lr_value: 4.58e-02, train Sum_time: 83.87, train Eval_EER: 9.04, train Best_EER: 8.09
