### ISSUE TITLE
请教一下说话人日志相关任务

### ISSUE THREAD

**Issue by MisakaMikoto-o** [modelscope/3D-Speaker#152]
你好，我最近试用了一下modelscope上的CAM++说话人日志-对话场景角色区分-通用模型，感觉很不错！我看见这个模型其实是由几个模型组成的，其中的CAM++说话人确认-中文-通用-200k-Spkrs模型应该是用来提取说话人embedding的，那么我在想理论上是不是能够做到提前用说话人确认模型将一些说话人声音保存为embeddings，然后调用说话人日志模型进行主持人分组任务时，不仅输出原有分组结果，还将每段分组分别与提前保存的embeddings进行比对，确认这些说话人是不是在说话人库中。如果这个功能有现成接口的话就最好啦，如果没有的话能不能给出修改意见，谢谢！比较菜见谅

我现在是使用modelscope上提供的这种方式调用模型的
```
# 版本要求 modelscope version 升级至最新版本 funasr 升级至最新版本
from modelscope.pipelines import pipeline
sd_pipeline = pipeline(
    task='speaker-diarization',
    model='damo/speech_campplus_speaker-diarization_common',
    model_revision='v1.0.0'
)
input_wav = 'https://modelscope.cn/api/v1/models/damo/speech_campplus_speaker-diarization_common/repo?Revision=master&FilePath=examples/2speakers_example.wav'
result = sd_pipeline(input_wav)
print(result)
# 如果有先验信息，输入实际的说话人数，会得到更准确的预测结果
result = sd_pipeline(input_wav, oracle_num=2)
print(result)
```

**Comment by MisakaMikoto-o** [comment]
我现在是使用modelscope上的这种方式调用模型的
`# 版本要求 modelscope version 升级至最新版本 funasr 升级至最新版本
from modelscope.pipelines import pipeline
sd_pipeline = pipeline(
    task='speaker-diarization',
    model='damo/speech_campplus_speaker-diarization_common',
    model_revision='v1.0.0'
)
input_wav = 'https://modelscope.cn/api/v1/models/damo/speech_campplus_speaker-diarization_common/repo?Revision=master&FilePath=examples/2speakers_example.wav'
result = sd_pipeline(input_wav)
print(result)
# 如果有先验信息，输入实际的说话人数，会得到更准确的预测结果
result = sd_pipeline(input_wav, oracle_num=2)
print(result)`

**Comment by wanghuii1** [comment]
根据result中的时间去提取某个角色的speaker embedding，然后和库中的embedding做对比就行了

**Comment by MisakaMikoto-o** [comment]
> 根据result中的时间去提取某个角色的speaker embedding，然后和库中的embedding做对比就行了

好的，还有一个问题就是模型推理时间好像比较久，有什么办法提高推理速度吗

**Comment by wanghuii1** [comment]
> > 根据result中的时间去提取某个角色的speaker embedding，然后和库中的embedding做对比就行了
> 
> 好的，还有一个问题就是模型推理时间好像比较久，有什么办法提高推理速度吗

如果处理大量数据，可以使用多进程同时调用多个pipeline来并行处理数据集
