### ISSUE TITLE
想请教一下怎么训练一个自己的说话人日志模型

### ISSUE THREAD

**Issue by wcqy-ye** [modelscope/3D-Speaker#153]
我看run_audio.sh里的内容应该是使用预定模型进行测试，我想请教怎么训练自己的说话人日志模型

**Comment by yfchenlucky** [comment]
说话人日志模型是VAD模型+说话人识别模型+说话人转换点定位模型结合聚类算法构成，你可以尝试从说话人识别模型训练开始，替换成自己的训练模型，需要调节聚类算法中的各参数。
