### ISSUE TITLE
CAM++流式推理

### ISSUE THREAD

**Issue by TungyuYoung** [modelscope/3D-Speaker#154]
您好，请教一下 CAM++ 的流式推理怎么做？

**Comment by wanghuii1** [comment]
可以固定每3s提取一次特征

**Comment by TungyuYoung** [comment]
> 可以固定每3s提取一次特征

我可以这样理解么？segment的部分放在最前面，每1.5s或者3s的片段传进来，然后过VAD和embedding calculation，再到后续的clustering之类的，然后实时地给出说话人分类的结果。

**Comment by yfchenlucky** [comment]
大致结构是这样的，但是中间具体过程比如聚类算法选择，类中心的更新等还需要打磨。

**Comment by TungyuYoung** [comment]
> 大致结构是这样的，但是中间具体过程比如聚类算法选择，类中心的更新等还需要打磨。

您好，我实现了大部份的功能。但我直接使用kmeans的话，当前时间段所给出的说话人label，和上一时间段的说话人label不会一一对应，即使是同几个说话人在说话。请问您有更好的建议吗？很抱歉再次打扰您了。
