### ISSUE TITLE
想请教关于数据预处理部分音频切分的长度

### ISSUE THREAD

**Issue by ParasiteM1G1** [modelscope/3D-Speaker#156]
prepare_data_csv.py中seg_dur的默认值大多是4s，但是cam++模型训3D-Speaker和Voxceleb的默认值都是3s，请问是怎么考虑的？是有做过对比实验3s的效果更好吗？都切分成3s的话，训练的时候设置的也是3s的chunk，会不会因此减少数据多样性？

**Comment by yfchenlucky** [comment]
seg_dur设置大于训练切分长度即可，我们没有严格对比过seg_dur数值对实验性能的影响。3D-Speaker和VoxCeleb中训练切分长度默认是3是根据经验设置可以修改。seg_dur增大会减小长音频在一个epoch中的训练次数，应该不会减少数据多样性。
