### ISSUE TITLE
请教一下模型部署相关问题

### ISSUE THREAD

**Issue by jiayuan666** [modelscope/3D-Speaker#157]
首先感谢你们团队对业界的贡献！

我已经使用erea2net_para模型在language identification任务上训练完了模型，测试集ACC也有95%.
目前打算将模型部署成一个API服务，能够接收音频文件返回语种结果，请问有什么建议吗？
另外，已经根据speakerlab/bin/下的脚本输出onnx文件，获得了extract_speaker_embedding、make_fbank_feature这两个文件，后续如何使用这两个文件呢？

谢谢你的时间

**Comment by yfchenlucky** [comment]
部署相关我们不太了解，可能不能给予建设性意见。你可以通过onnx转出脚本直接获取speaker embedding用于后续需求。

**Comment by GeekOrangeLuYao** [comment]
如果需要转换成language identification任务进行部署，这里的extract_speaker_embedding的脚本可能不太适用，因为language identification是固定的输出种类，而extract_speaker_embedding.cpp针对speaker verification任务，因此导出模型时，丢掉了最后的classifier。

我的建议是你需要在export onnx时，将你训练好的eres2net模型和对应的classifier wrap成一个模型，随后再送入export_onnx_file，你需要验证这个模型的输出纬度是否和你分类的种类数一致。这样理论上将使得extract_speaker_embedding.cpp输出为一个种类数纬度的vector，选取最大的那个作为模型的输出language。
