### ISSUE TITLE
验证运行

### ISSUE THREAD

**Issue by brccqs** [modelscope/3D-Speaker#161]
小白，请教一下关于说话人分类验证部分，应该怎么操作。

**Comment by yfchenlucky** [comment]
可以参考readme中的推理代码：
# Install modelscope
pip install modelscope
# ERes2Net trained on 200k labeled speakers
model_id=iic/speech_eres2net_sv_zh-cn_16k-common
# Run CAM++ or ERes2Net inference
python speakerlab/bin/infer_sv.py --model_id $model_id
# Run batch inference
python speakerlab/bin/infer_sv_batch.py --model_id $model_id --wavs $wav_list

**Comment by brccqs** [comment]
> 可以参考readme中的推理代码：
> 
> pip install modelscope model_id=iic/speech_eres2net_sv_zh-cn_16k-common python speakerlab/bin/infer_sv.py --model_id $model_id

好的，感谢
