### ISSUE TITLE
Windows环境下可以使用预训练模型进行推理吗

### ISSUE THREAD

**Issue by QQ-moon-QQ** [modelscope/3D-Speaker#163]
按照文档配置环境的过程中，出现了冲突，如下：
ERROR: Ignored the following versions that require a different python version: 0.59.0 Requires-Python >=3.9; 0.59.0rc1 Requires-Python >=3.9; 0.59.1 Requires-Python >=3.9; 0.60.0 Requires-Python >=3.9; 0.60.0rc1 Requires-Python >=3.9; 0.61.0rc1 Requires-Python >=3.10; 4.47.0 Requires-Python >=3.9.0
ERROR: Could not find a version that satisfies the requirement pyannote (from versions: none)
ERROR: No matching distribution found for pyannote
我尝试用以下方法解决问题，但还是失败了。
```
pip install pyannote.audio -i https://mirrors.aliyun.com/pypi/simple/
```
请问有什么解决方法吗？

**Comment by wanghuii1** [comment]
可以先忽略，应该不影响运行

**Comment by QQ-moon-QQ** [comment]
好的，我尝试一下。
