### ISSUE TITLE
在cn_celeb测试集实际测试EER与报告不一致

### ISSUE THREAD

**Issue by jet-yangqs** [modelscope/3D-Speaker#164]
感谢作者的贡献。我在复现cam++模型的测试结果时，遇到了实际测试的结果4.70%与报告的结果4.32%不一致的问题，请问可能有哪些原因呢？ 是你们上传的模型和报告的结果没有完全对应，还是我测试有什么问题？请给一些建议。

模型：你们在model_scope中开源的使用200k说话人数据集训练的cam++模型：https://modelscope.cn/models/iic/speech_campplus_sv_zh-cn_16k-common/summary，该模型在cn_celeb测试集上报告的EER=4.32%
<img width="387" alt="image" src="https://github.com/user-attachments/assets/1cf8c913-4367-443a-86d3-b580f7adfc9d">

我使用infer_sv.py内的模型加载方式加载模型，然后使用run.sh里面stage4和5提取embedding和计算分数，EER结果为4.70%
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/4b1b6288-5da6-4e7f-ac0e-fbc3ffdc74d5">

**Comment by wanghuii1** [comment]
测试中一个人是有多个注册音频。
如果将多个注册音频拼接后提取一个embedding作为注册embedding，和测试embedding计算得分，会得到这个结果。
如果将每个注册音频单独提取embedding后取平均作为注册embedding，会获得4.3%的EER。

**Comment by jet-yangqs** [comment]
非常感谢你的解答。
我还发现，如果在3d-speaker训练集上训练的模型，在3d-speaker测试集测试，效果和报告的基本一致，模型：https://modelscope.cn/models/iic/speech_campplus_sv_zh-cn_3dspeaker_16k/summary
报告：
<img width="664" alt="image" src="https://github.com/user-attachments/assets/32c18169-4588-4240-8433-506a65c2f28a">
实际测试：
<img width="1307" alt="image" src="https://github.com/user-attachments/assets/3c2369b0-b0ab-4520-a3e1-6e877bae9d03">
如果使用200k speakers训练的模型（该模型在cn_celeb上报告的结果为eer=4.32%）在3d-speaker的测试集上测试，EER很高，
模型：https://modelscope.cn/models/iic/speech_campplus_sv_zh-cn_16k-common/summary
实际在3d-speaker上的测试结果：
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/947eda14-5bd1-40ff-bf16-db1fdb5b7fdd">
请问这个现象是符合预期的吗？在3d-speaker测试集上的EER较高。

**Comment by wanghuii1** [comment]
200k speakers模型训练数据未包含3d-speaker训练集，非同源测试效果会比较差

**Comment by jet-yangqs** [comment]
好的，感谢你的耐心解答。
